export const USER_LOOGIN_REQUEST = 'USER_LOOGIN_REQUEST'
export const USER_LOOGIN_SUCCESS = 'USER_LOOGIN_SUCCESS'
export const USER_LOOGIN_FAIL = 'USER_LOOGIN_FAIL'

export const USER_LOGOUT = 'USLOGOUT'