export const USER_LOGIN_REQUEST = 'USER_LOOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOOGIN_FAIL'

export const USER_LOGOUT = 'USLOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_REGISTER_FAIL'
export const USER_DETAILS_RESET = 'USER_REGISTER_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_REGISTER_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_REGISTER_FAIL'